version: '3.4'
services:
  Jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    ports:
      - "8080:8080"
      - 50000:50000
    container_name: jenkins
    volumes:
      -  /jenkins:/var/jenkins_home